# Exercises: Python basics I

This notebook accompanies the lecture notebooks:

- `00_Computers_and_programming.ipynb`
- `01_Atomic_types.ipynb`
- `02_Containers.ipynb`
- `03_Conditionals.ipynb`

## How to work

1. Write your own code in the empty code cell below each task.
2. Try for a few minutes before opening the hint.
3. Reveal the full solution only after you have written an attempt.
4. Use descriptive variable names and make sure you understand every line you keep.
5. When you finish, restart the kernel and run the notebook from top to bottom.

The hints and solutions are collapsed. Click the small triangle to reveal them.

## 1. Types, conversion and operators

A student's monthly income was read from a form and is therefore stored as a string.

1. Print the value and type of `monthly_income_text`.
2. Convert it to an integer called `monthly_income`.
3. Compute how much money is left after rent and the food budget.
4. Compute how many complete amounts of 500 DKK fit into the money left. Also compute the remaining number of DKK. Use `//` and `%`.
5. Create a boolean called `has_at_least_5000_left` that is `True` when at least 5,000 DKK remain.
6. Print all results.

In [1]:
monthly_income_text = '15450'
rent = 6800
food_budget = 2750

In [2]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

Use `int()` for the conversion. The operator `//` gives the number of complete 500 DKK amounts, while `%` gives the remainder.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
print('monthly_income_text =', monthly_income_text)
print('type =', type(monthly_income_text))

monthly_income = int(monthly_income_text)
money_left = monthly_income - rent - food_budget

full_500_amounts = money_left // 500
remaining_dkk = money_left % 500
has_at_least_5000_left = money_left >= 5000

print('monthly_income =', monthly_income)
print('money_left =', money_left)
print('full_500_amounts =', full_500_amounts)
print('remaining_dkk =', remaining_dkk)
print('has_at_least_5000_left =', has_at_least_5000_left)
```

You should obtain 5,900 DKK left, 11 complete amounts of 500 DKK, a remainder of 400 DKK, and `True`.

</details>

## 2. A budget check with booleans

A student has a weekly budget of 300 DKK. A lunch costs 50 DKK and one bus trip costs 24 DKK.

The student considers two weekly plans:

- **Plan A:** 4 lunches and 4 bus trips
- **Plan B:** 5 lunches and 3 bus trips

For each plan:

1. Compute total expenditure.
2. Create a boolean that is `True` when the plan is affordable.
3. Compute the money left after the purchases. A negative number means that the plan is too expensive.
4. Print the expenditure, the boolean and the money left.

In [3]:
weekly_budget = 300
lunch_price = 50
bus_trip_price = 24

plan_a_lunches = 4
plan_a_bus_trips = 4

plan_b_lunches = 5
plan_b_bus_trips = 3

In [4]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

For Plan A, begin with:

```python
plan_a_expenditure = lunch_price * plan_a_lunches + bus_trip_price * plan_a_bus_trips
```

Use `<=` to check whether expenditure is no larger than the budget.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
plan_a_expenditure = lunch_price * plan_a_lunches + bus_trip_price * plan_a_bus_trips
plan_a_affordable = plan_a_expenditure <= weekly_budget
plan_a_money_left = weekly_budget - plan_a_expenditure

print('Plan A expenditure =', plan_a_expenditure)
print('Plan A affordable =', plan_a_affordable)
print('Plan A money left =', plan_a_money_left)

plan_b_expenditure = lunch_price * plan_b_lunches + bus_trip_price * plan_b_bus_trips
plan_b_affordable = plan_b_expenditure <= weekly_budget
plan_b_money_left = weekly_budget - plan_b_expenditure

print('Plan B expenditure =', plan_b_expenditure)
print('Plan B affordable =', plan_b_affordable)
print('Plan B money left =', plan_b_money_left)
```

Plan A costs 296 DKK and is affordable. Plan B costs 322 DKK and is not affordable.

</details>

## 3. Lists and loops: revenue growth

A small firm's annual revenue, measured in million DKK, is stored in a list:

```python
revenue = [64.0, 96.0, 120.0, 150.0]
```

1. Print the first two observations and the last two observations using slicing.
2. Compute the growth rate from the first to the second year using

$$
\text{growth rate} = \frac{\text{new revenue}}{\text{old revenue}} - 1.
$$

3. Create an empty list called `growth_rates`.
4. Use a `for` loop and `range(len(revenue)-1)` to compute all growth rates. Append each result to `growth_rates`.
5. Print `growth_rates`.
6. Print whether the number of growth rates equals the number of revenue observations minus one.

In [5]:
revenue = [64.0, 96.0, 120.0, 150.0]

In [6]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

Inside the loop, use `year_index` to access two neighbouring observations:

- old revenue: `revenue[year_index]`
- new revenue: `revenue[year_index + 1]`

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
print('first two observations =', revenue[:2])
print('last two observations =', revenue[-2:])

first_growth_rate = revenue[1] / revenue[0] - 1
print('first growth rate =', first_growth_rate)

growth_rates = []

for year_index in range(len(revenue) - 1):
    old_revenue = revenue[year_index]
    new_revenue = revenue[year_index + 1]
    growth_rate = new_revenue / old_revenue - 1
    growth_rates.append(growth_rate)

print('growth_rates =', growth_rates)
print('correct number of growth rates =', len(growth_rates) == len(revenue) - 1)
```

You should obtain `[0.5, 0.25, 0.25]`.

</details>

## 4. Copying versus referencing

Run the code below only after predicting the result.

1. What will `baseline_output` contain after `policy_output[1] = 95.0`?
2. Run the cell and inspect both lists.
3. In the next code cell, rewrite the example using `.copy()` so that changing the policy scenario does not change the baseline.
4. Print whether the two variables refer to the same object by using `is`.

In [7]:
baseline_output = [100.0, 102.0, 104.0, 106.0]
policy_output = baseline_output

policy_output[1] = 95.0

print('policy_output =', policy_output)
print('baseline_output =', baseline_output)

policy_output = [100.0, 95.0, 104.0, 106.0]
baseline_output = [100.0, 95.0, 104.0, 106.0]


In [8]:
# Write your corrected version here

<details>
<summary><strong>Show hint</strong></summary>

The line `policy_output = baseline_output` creates a second reference to the same list. Use `baseline_output.copy()` when creating the policy scenario.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
baseline_output = [100.0, 102.0, 104.0, 106.0]
policy_output = baseline_output.copy()

policy_output[1] = 95.0

print('policy_output =', policy_output)
print('baseline_output =', baseline_output)
print('same object =', policy_output is baseline_output)
```

The baseline remains `[100.0, 102.0, 104.0, 106.0]`, and `same object` is `False`.

</details>

## 5. Dictionaries and a household shopping basket

Prices and quantities are stored in two dictionaries. Prices are in DKK.

1. Create an empty dictionary called `spending_by_good` and set `total_spending = 0.0`.
2. Loop over `prices.items()`.
3. For each good, look up its quantity in `quantities`.
4. Compute spending on the good and store it in `spending_by_good`.
5. Add the amount to `total_spending`.
6. Print the good, price, quantity and spending inside the loop.
7. After the loop, print `spending_by_good` and `total_spending`.
8. Use an `if` statement to print the price of butter if `'butter'` is in `prices`. Otherwise, print that butter is not in the shopping basket.

In [9]:
prices = {'bread': 22.0, 'milk': 12.0, 'coffee': 48.0}
quantities = {'bread': 2, 'milk': 3, 'coffee': 1}

In [10]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

The loop can begin with:

```python
for good, price in prices.items():
```

Inside the loop, use `quantities[good]` to find the matching quantity.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
spending_by_good = {}
total_spending = 0.0

for good, price in prices.items():
    quantity = quantities[good]
    spending = price * quantity
    spending_by_good[good] = spending
    total_spending += spending

    print(good, ': price =', price, ', quantity =', quantity, ', spending =', spending)

print('spending_by_good =', spending_by_good)
print('total_spending =', total_spending)

if 'butter' in prices:
    print('butter price =', prices['butter'])
else:
    print('butter is not in the shopping basket')
```

The total spending is 128 DKK.

</details>

## 6. Conditionals inside a loop: a simple tax schedule

Consider the following **fictional** tax schedule. Income is measured in thousand DKK.

- No tax on income up to 50.
- 20 percent tax on the part of income between 50 and 100.
- 40 percent tax on the part of income above 100.

This implies:

$$
\text{tax}(y) =
\begin{cases}
0 & \text{if } y \leq 50, \\
0.20(y-50) & \text{if } 50 < y \leq 100, \\
0.20 \cdot 50 + 0.40(y-100) & \text{if } y > 100.
\end{cases}
$$

Before writing code, calculate the tax for incomes 75 and 150 by hand.

Then:

1. Create an empty list called `taxes`.
2. Loop over `incomes`.
3. Use `if`, `elif` and `else` to calculate the tax.
4. Append each tax to `taxes`.
5. Compute after-tax income.
6. Print income, tax and after-tax income inside the loop.
7. Print the complete list of taxes after the loop.

In [11]:
incomes = [40.0, 50.0, 75.0, 100.0, 150.0]

In [12]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

Use the conditions in this order:

```python
if income <= 50:
elif income <= 100:
else:
```

The second branch is reached only when the first condition was `False`, so it already implies that income is above 50.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

```python
taxes = []

for income in incomes:
    if income <= 50:
        tax = 0.0
    elif income <= 100:
        tax = 0.20 * (income - 50)
    else:
        tax = 0.20 * 50 + 0.40 * (income - 100)

    taxes.append(tax)
    after_tax_income = income - tax

    print('income =', income, ', tax =', tax, ', after-tax income =', after_tax_income)

print('taxes =', taxes)
```

The taxes are `[0.0, 0.0, 5.0, 10.0, 30.0]`.

</details>

## 7. Optional: a `while` loop and a savings target

A household starts with savings of 1,000 DKK and adds 750 DKK each month.

1. Set `current_savings` equal to `initial_savings` and set `months = 0`.
2. Use a `while` loop to continue saving while current savings are below the target of 5,000 DKK.
3. In each iteration, add the monthly saving and increase `months` by one.
4. Print the number of months and the final savings.

**Extension:** Every third month, the household also pays an unexpected expense of 500 DKK. Add an `if` statement inside the loop and find the new number of months.

In [13]:
initial_savings = 1000
monthly_saving = 750
target_savings = 5000

In [14]:
# Write your code here

<details>
<summary><strong>Show hint</strong></summary>

The loop condition is `current_savings < target_savings`.

For the extension, `months % 3 == 0` is `True` every third month.

</details>

<details>
<summary><strong>Reveal solution</strong></summary>

Basic version:

```python
current_savings = initial_savings
months = 0

while current_savings < target_savings:
    current_savings += monthly_saving
    months += 1

print('months =', months)
print('current_savings =', current_savings)
```

The target is reached after 6 months.

Extension:

```python
current_savings = initial_savings
months = 0

while current_savings < target_savings:
    months += 1
    current_savings += monthly_saving

    if months % 3 == 0:
        current_savings -= 500

print('months with expenses =', months)
print('current_savings =', current_savings)
```

With the extra expense, the target is reached after 7 months.

</details>

## Final check

Before you finish:

1. Save the notebook.
2. Restart the kernel.
3. Run all cells from top to bottom.
4. Confirm that there are no errors.
5. Make sure you can explain what every variable and every line in your own solutions does.

A notebook that only works because cells were run in a special order is not finished.